### ISSUE TITLE
Aggregation of http codes in fields instead of measurements

### ISSUE THREAD

**Issue by ghost** [jib/mod_statsd#22]
Good day to you,
Using telegraf / Statsd & influxdb...

I am trying to configure and use this plugin for our environment. However, I see that our measurement will fill in with all the possible codes from http. How can I have the "GET"/"POST"/HEAD" & "200"/"302", etc in the fields instead of measurments and group them under a single measurement?
![image](https://user-images.githubusercontent.com/7452857/42951563-7649115c-8b44-11e8-8e40-21ff0e0bf1fc.png)

![image](https://user-images.githubusercontent.com/7452857/42951698-ce3063e8-8b44-11e8-9279-762800de203c.png)

**Comment by ghost** [comment]
Finally worked out.
SP

**Comment by kimor79** [comment]
just in case you didn't see it: https://github.com/jib/mod_statsd/pull/18
